# docker-compose.yml
version: '3.8'

services:
  claude-connector:
    # The image tag will be replaced by the GitHub Actions workflow
    image: ghcr.io/korjavin/claude_connector:ca4cae21d64db6b803d9115d5263a606575098aa
    container_name: claude-connector-service
    ports:
      - "8080:8080"
    volumes:
      - claude_data:/data:ro
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.claude-connector.rule=Host(`${CLAUDE_DOMAIN:-claude-connector.yourdomain.com}`)"
      - "traefik.http.routers.claude-connector.entrypoints=websecure"
      - "traefik.http.routers.claude-connector.tls.certresolver=${TLS_RESOLVER:-myresolver}"
      - "traefik.http.services.claude-connector.loadbalancer.server.port=8080"
    networks:
      - claude-network
    restart: unless-stopped

volumes:
  claude_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/claude-connector/data

networks:
  claude-network:
    external: true