# docker-compose.prod.yml - Production deployment configuration
version: '3.8'

services:
  claude-connector:
    # Production image from GitHub Container Registry
    image: ghcr.io/korjavin/claude_connector:latest
    container_name: claude-connector-prod
    ports:
      - "8080:8080"
    volumes:
      - claude_data:/data:ro
    env_file:
      - .env
    environment:
      - MCP_SERVER_PORT=${MCP_SERVER_PORT:-8080}
      - CSV_FILE_PATH=${CSV_FILE_PATH:-/data/medical_data.csv}
      - API_SECRET_KEY=${API_SECRET_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.claude-connector.rule=Host(`${CLAUDE_DOMAIN:-claude-connector.yourdomain.com}`)"
      - "traefik.http.routers.claude-connector.entrypoints=websecure"
      - "traefik.http.routers.claude-connector.tls.certresolver=${TLS_RESOLVER:-myresolver}"
      - "traefik.http.services.claude-connector.loadbalancer.server.port=8080"
    networks:
      - claude-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  claude_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/claude-connector/data

networks:
  claude-network:
    external: true
    name: ${NETWORK_NAME:-claude-network}