# .github/workflows/deploy.yml
name: Deploy Claude Connector

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          build-args: |
            COMMIT_SHA=${{ github.sha }}

      - name: Update and commit docker-compose.yml
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git checkout -B deploy
          sed -i "s|image: ghcr.io/.*/.*:.*|image: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}|g" docker-compose.yml
          git add docker-compose.yml
          git commit -m "ci: Update image tag to ${{ github.sha }}"
          git push origin deploy --force

      - name: Trigger Portainer Redeploy Webhook (Optional)
        continue-on-error: true
        run: |
          if [ -n "$PORTAINER_HOOK" ]; then
            echo "Triggering Portainer webhook..."
            curl -X POST "$PORTAINER_HOOK" \
              -H "Content-Type: application/json" \
              -d "{\"source\": \"github-actions\", \"commit\": \"${{ github.sha }}\"}" \
              --fail --silent --show-error || echo "Webhook call failed"
            echo "Portainer webhook triggered"
          else
            echo "PORTAINER_REDEPLOY_HOOK secret not configured, skipping webhook"
          fi
        env:
          PORTAINER_HOOK: ${{ secrets.PORTAINER_REDEPLOY_HOOK }}